### ISSUE TITLE
Is there a proof that setlx is turing complete?

### ISSUE THREAD

**Issue by jendrikw** [herrmanntom/setlX#6]
I strongly suspect that setlx is turing complete, but I haven't found a proof yet. Is there a proof available somewhere?

**Comment by herrmanntom** [comment]
It surely is. However you are right - there is no format prof yet.

**Comment by jendrikw** [comment]
Since there wasn't a proof available I made my own brainfuck interpreter in setlx. You can find it here: https://github.com/Jendrik3/setlx-brainfuck
What do you think of it?

**Comment by herrmanntom** [comment]
Looks very interesting. I played around with it a little bit, and it seems to work :-)
